### ISSUE TITLE
Pixelwar colors are off for RGBA

### ISSUE THREAD

**Issue by LeoDJ** [defnull/pixelflut#10]
I recently started playing with Pixelflut.
On Windows - in my case - python pixelflut is way too slow (900px/s) and pixelnuke won't compile (obviously).
So I chose java Pixelwar, which is way faster and compiled it using maven. But there I have another problem:

- colors are scrambled. (red renders as blue)
- if pixels are set with alpha channel, but full opacity, it still renders them as transparent

When no alpha channel is set, it renders colors without a problem.

I didn't start looking into it yet, maybe it's something easy. I just wanted to document that problem first.

![grafik](https://user-images.githubusercontent.com/5898657/38978755-9641b42e-43b8-11e8-9c3a-14ab0fde6ccf.png)
![grafik](https://user-images.githubusercontent.com/5898657/38978896-060bc43e-43b9-11e8-98aa-eadff4d4dc45.png)
![grafik](https://user-images.githubusercontent.com/5898657/38979358-30926eaa-43ba-11e8-934c-e625336b7749.png)

**Comment by defnull** [comment]
Oh, looks like the `pixelwar` implementation parses colors as `ARGB` instead of `RGBA`. Thats a bug ^^

**Comment by LeoDJ** [comment]
Yeah, I'm currently trying to fix it, seems simple enough
