### ISSUE TITLE
Add Support for animation feaure like in gartic phone

### ISSUE THREAD

**Issue by 8bignic8** [defnull/pixelflut#21]
Hey, 

I think It might be funny to add a fature, where you could gray out the Background after a time or a treshhold of Pixels drawn it gets saved, and drawn over. 
The goal could be to make a Gif, Video or Animation. It could be possible to request the last drawn picture to change and add to it.

If this makes no sense, just declare the Issue as resolved. 

Example: 
https://www.youtube.com/watch?v=yRNxEbtkrgA

Have an nice Day :)

**Comment by H3wastooshort** [comment]
i think this goes a bit against the pixelflut concept of a super simple (and inefficient) protocol

**Comment by defnull** [comment]
Pixelflut is 'feature complete' and I will only merge technical improvements or bug fixes. New features are not planned. But feel free to fork and experiment with your idea :)
