### ISSUE TITLE
Clean Quit?

### ISSUE THREAD

**Issue by ccoenen** [defnull/pixelflut#4]
Is there a way to exit pixelflut cleanly? I have tried adding a key (<kbd>Q</kbd>) which calls `sys.exit(0)`, but this does not work. <kbd>Ctrl</kbd>+<kbd>C</kbd> does also not work.

I tried killing the process (regular SIGTERM and also SIGKILL), but I don't return to my regular terminal afterwards either way. Right now, I'm simply power-cycling my Raspberry Pi.

**Comment by ccoenen** [comment]
In case that's relevant: It's a Raspberry Pi 3 on an up to date Raspbian / Debian 8 (jessie) and Python 2.7.9

**Comment by ccoenen** [comment]
Judging by [this query](http://stackoverflow.com/search?q=%5Bpygame%5D+quit), this appears to be a common problem with pygame. From what I read, it may also be a driver problem and not at all related to pixelflut itself. If it's just my setup, feel free to close the issue.

**Comment by defnull** [comment]
If you find anything that can be changed in pixelflut to work aground this pygame bug, please re-open or submit a pull request.
